require('plugin_config.lsp')
require('plugin_config.formatter')
require('plugin_config.lint')
require('plugin_config.cmp')
require('plugin_config.gitsigns')
require('plugin_config.telescope')
require('plugin_config.whichkey')
require('plugin_config.todo-comments')
require('plugin_config.harpoon')
require('plugin_config.treesitter')
require('plugin_config.autopairs')
require('plugin_config.undotree')
require('plugin_config.nvimtree')
require('plugin_config.statusline')
require('plugin_config.translate')
require('plugin_config.keymaps')

