local options = {
  syntax = 'on',
  filetype = 'plugin_indent_on',
  fileencoding = 'utf8',
  virtualedit = 'block',
  clipboard = 'unnamedplus',
  completeopt = { 'menu', 'menuone', 'noselect' },
  signcolumn = 'yes',
  mouse = 'a',
  colorcolumn = '80',
  guicursor = '',
  exrc = true,
  autoread = true,
  hidden = true,
  splitright = true,
  splitbelow = true,
  writebackup = false,
  cursorline = false,
  wrap = false,
  swapfile = false,
  backup = false,
  ignorecase = true,
  autoindent = true,
  smartcase = true,
  timeout = true,
  pumheight = 10,
  timeoutlen = 250,
  updatetime = 250,
  scrolloff = 10,
  cmdheight = 1,
  conceallevel = 0,
  laststatus = 3,
  number = true,
  relativenumber = true,
  termguicolors = true,
  tabstop = 2,
  softtabstop = 2,
  shiftwidth = 2,
  expandtab = true,
  smartindent = true,
  hlsearch = false,
  incsearch = true,
  winminwidth = 0,
  winminheight = 0,
}

for k, v in pairs(options) do
  vim.opt[k] = v
end

